### PR TITLE
Generalize linear interpolator to compute values based on an arbitrary function and context

### LINKED ISSUE #3: Streamline linear interpolation
Currently using my MTE201 linear interpolation code method for both drag and Cd calculation. What I would ideally like is the ability to pass an arbitrary number of curves (specified by polynomials), and interpolate between them based on the input reference area. As an example, the current code looks like this, for 3 curves at 0%, 50%, and 100%:

Calculate and correct drag from curves
` /**@return drag force value based on curves produced by Ansys at fixed extensions
     * @param velocity is used to lookup drag value
     * @param extension MUST BE EITHER 0, 0.5, or 1. Used to determing which function to use and to adjust for rocket area
     * */
    private static double lookup_drag(double fixed_extension, double velocity) {
        double drag;
        //System.out.println("vel input to drag calc:" + velocity + "m/s");
        if (Math.abs(fixed_extension) < tol) {
            drag = (0.0035 * velocity * velocity) + (0.1317 * velocity) - 5.0119;
        } 
        else if (Math.abs(fixed_extension - 0.5) < tol) {
            drag = (0.0045 * velocity * velocity) + (0.1031 * velocity) - 3.8231;
        } 
        else { // fixed_extension == 1
            drag = (0.006 * velocity * velocity) + (0.1038 * velocity) - 4.2522;
        }

        return drag / rocket_area(fixed_extension) / air_density(SIM_ALTITUDE); //adjust simulation drag for altitude and extension amount
    }`
    
    Interpolate between curve values
`double dx = 0.5;
        double y_1;
        double y_2;
        double x_1;
        if (extension > 0.5) {
            x_1 = 0.5;
            y_1 = lookup_drag(0.5, velocity);
            y_2 = lookup_drag(1, velocity);
        }
        else { // extension < 0.5
            x_1 = 0;
            y_1 = lookup_drag(0, velocity);
            y_2 = lookup_drag(0.5, velocity);
        }
        System.out.println("y1: " + y_1 + " y2:" + y_2);
        drag = y_1 + (y_2-y_1) / dx * (extension - x_1);
        drag = air_density(altitude) * rocket_area(extension) * drag;

         System.out.println("Fdrag:" + drag + "N");
        return drag;`

### PR DESCRIPTION
**Pull request by patrick-gu**
The idea here is that we can compute drag values for each airbrake extension amount based on the context, then use linear interpolation to compute the drag amount for some specific airbrake extension.

It's not particularly good to have excessive abstraction, but I think this is reasonable for this case, so that the linear interpolation code can be logically separated from the code for computing drag force as a function of velocity and altitude.

Closes #3.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7)

### CODE REVIEW

**Comment by celery6** [comment]
Seems like Armaan and Richard are looking into making a 3-var eq that would remove the need for linear interpolation. https://waterloorocketry.slack.com/archives/C05EUQLFP4J/p1709656065814399

How about we put this pr on hold till they look into that?

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @celery6, @Joe-Joe-Joe-Joe, and @patrick-gu)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7#-NtT0GFe0q80vRmLqnBE):*
After much discussion me, Pat and Christine we have come up with a complete restructure :stuck_out_tongue_winking_eye: 

1. The core interface behind everything will be `interpolator`
2. We define the class `SingleVarLinInterp` and use it as a primitive for other classes
3. In practice, we will define CoefDragInterp and use it in all the coefficient of drag calculations



_Code snippet:_
```
public interface Interpolator<InputData> {
  public double interpolate(InputData d);
}

public class SingleVarLinInterp extends Interpolator<double> {
  public SingleVarLinInter(double[] args, double[] vals) {
    ...  
  }
  
  @override
  public double interpolate(double d) {
    ...  
  }
}

public CoefOfDragInterp extends Interpolator<CoefDragInterp.data> {
  public CoefOfDragInterp(...) {
    ...  
  }
  
  @override
  public double interpolate(...) {
    ...  
  }
}
```

**Review by KavinSatheeskumar — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @celery6, @Joe-Joe-Joe-Joe, and @patrick-gu)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7#-NtT0GFe0q80vRmLqnBE):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

After much discussion me, Pat and Christine we have come up with a complete restructure :stuck_out_tongue_winking_eye: 

1. The core interface behind everything will be `interpolator`
2. We define the class `SingleVarLinInterp` and use it as a primitive for other classes
3. In practice, we will define CoefDragInterp and use it in all the coefficient of drag calculations
</blockquote></details>

Ok I forgot to add that CoefDragInterp has an encapsulated class CoefOfDragData

**Comment by Joe-Joe-Joe-Joe** [comment]
No comments on the class structure. You guys go wild.

> How about we put this pr on hold till they look into that?

If it wasn't clear, we did look into that, and the drag model that was merged from #2 is the one we are planning to use for the rest of this design cycle. Which is to say, interpolate drag from velocity and fixed extension, then correction factors for true area and altitude. So yes, 3 vars, but no, no analytical model (just velocity-drag level curves)

**Review by patrick-gu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @celery6 and @Joe-Joe-Joe-Joe)

___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/simulated/SimulatedCdInterpolator.java` line 30 at r2](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7#-NtXY-rB64aDgG2YgfS4:-NtXY-rCDd5IrlNnwUhn:b-amm7k0) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/0ed3549f8bc255f1fddb985ace77414b8a5fc707/src/main/java/com/waterloorocketry/airbrakeplugin/simulated/SimulatedCdInterpolator.java#L30)):*
> ```Java
>         NavigableMap<Double, Double> m = new ComputedNavigableMap<>(fs, (f) -> f.compute(data.velocity));
>         LinearInterpolator interp = new LinearInterpolator(m);
>         return interp.compute(data.extension);
> ```

I think this is essentially the point of this refactoring - so that we can compose computations like this

**Review by celery6 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7)* status: 0 of 11 files reviewed, 4 unresolved discussions (waiting on @Joe-Joe-Joe-Joe and @patrick-gu)

___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/simulated/SimulatedCdInterpolator.java` line 28 at r2](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7#-NtseM0T2iUeY_4Gltcg:-NtseM0T2iUeY_4Gltch:buqfu7v) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/0ed3549f8bc255f1fddb985ace77414b8a5fc707/src/main/java/com/waterloorocketry/airbrakeplugin/simulated/SimulatedCdInterpolator.java#L28)):*
> ```Java
>     @Override
>     public double compute(Data data) {
>         NavigableMap<Double, Double> m = new ComputedNavigableMap<>(fs, (f) -> f.compute(data.velocity));
> ```

Could we name this something other than just 'm'
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/simulated/SimulatedCdInterpolator.java` line 29 at r2](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7#-NtseQ2S3JdiAA5ftw-p:-NtseQ2S3JdiAA5ftw-q:b-lbi3gc) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/0ed3549f8bc255f1fddb985ace77414b8a5fc707/src/main/java/com/waterloorocketry/airbrakeplugin/simulated/SimulatedCdInterpolator.java#L29)):*
> ```Java
>     public double compute(Data data) {
>         NavigableMap<Double, Double> m = new ComputedNavigableMap<>(fs, (f) -> f.compute(data.velocity));
>         LinearInterpolator interp = new LinearInterpolator(m);
> ```

Can this be restructured somehow to avoid creating a new instance of LinearInterpolator everytime compute() is called?

**Review by patrick-gu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @celery6, @Joe-Joe-Joe-Joe, and @KavinSatheeskumar)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7#-NtT0GFe0q80vRmLqnBE):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Ok I forgot to add that CoefDragInterp has an encapsulated class CoefOfDragData
</blockquote></details>

Done.
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/simulated/SimulatedCdInterpolator.java` line 28 at r2](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7#-NtseM0T2iUeY_4Gltcg:-Ntuwqpl1QW10qzfgknT:b-896fix) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/0ed3549f8bc255f1fddb985ace77414b8a5fc707/src/main/java/com/waterloorocketry/airbrakeplugin/simulated/SimulatedCdInterpolator.java#L28)):*
<details><summary><i>Previously, celery6 (celery) wrote…</i></summary><blockquote>

Could we name this something other than just 'm'
</blockquote></details>

Done.
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/simulated/SimulatedCdInterpolator.java` line 29 at r2](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7#-NtseQ2S3JdiAA5ftw-p:-NtuwrJI8tWcnXhfod4b:b-2uii74) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/0ed3549f8bc255f1fddb985ace77414b8a5fc707/src/main/java/com/waterloorocketry/airbrakeplugin/simulated/SimulatedCdInterpolator.java#L29)):*
<details><summary><i>Previously, celery6 (celery) wrote…</i></summary><blockquote>

Can this be restructured somehow to avoid creating a new instance of LinearInterpolator everytime compute() is called?
</blockquote></details>

I think this is a consequence of the API design. We are essentially interpolating over new data each time, so we create a new interpolator. I agree that intuitively, it feels undesirable to instantiate a new linear interp calculator in each call. However, `ComputedNavigableMap` and `LinearInterpolator` are essentially designed to be free abstractions, in that they don't really do any unnecessary calculations in their constructors or methods. Especially with runtime optimization, this probably doesn't affect speed at all.

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @celery6, @Joe-Joe-Joe-Joe, and @patrick-gu)

___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/simulated/SimulatedCdInterpolator.java` line 27 at r3](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7#-Nv3H9JF7LATlIrXUMST:-Nv3H9JF7LATlIrXUMSU:b-zgo7kl) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/cff351a9c5995b7feea9fd8251a29bb2d55f74ab/src/main/java/com/waterloorocketry/airbrakeplugin/simulated/SimulatedCdInterpolator.java#L27)):*
> ```Java
> 
>     @Override
>     public double compute(Data data) {
> ```

Add a comment here about how `ComputedNavigableMap` is lazy
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/util/ComputedNavigableMap.java` line 10 at r3](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7#-Nv3HwGh99v3l19tMg18:-Nv3HwGh99v3l19tMg19:b-bpnuz) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/cff351a9c5995b7feea9fd8251a29bb2d55f74ab/src/main/java/com/waterloorocketry/airbrakeplugin/util/ComputedNavigableMap.java#L10)):*
> ```Java
>  * A {@link ComputedSortedMap} which is also a {@link NavigableMap}
>  */
> public class ComputedNavigableMap<K, V, R> extends ComputedSortedMap<K, V, R> implements NavigableMap<K, R> {
> ```

1. Add some comments to explain what ComputedSortedMap and ComputedMap are for
2. Maybe rename all of these to "lazy*"
3. See if anything exists in the stdlib

**Review by patrick-gu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @celery6, @Joe-Joe-Joe-Joe, and @KavinSatheeskumar)

___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/simulated/SimulatedCdInterpolator.java` line 27 at r3](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7#-Nv3H9JF7LATlIrXUMST:-NwXeohdEh8xE-5QaODe:b-896fix) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/cff351a9c5995b7feea9fd8251a29bb2d55f74ab/src/main/java/com/waterloorocketry/airbrakeplugin/simulated/SimulatedCdInterpolator.java#L27)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Add a comment here about how `ComputedNavigableMap` is lazy
</blockquote></details>

Done.
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/util/ComputedNavigableMap.java` line 10 at r3](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7#-Nv3HwGh99v3l19tMg18:-NwXephd6ub9PzupMMF7:b-nh8uh9) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/cff351a9c5995b7feea9fd8251a29bb2d55f74ab/src/main/java/com/waterloorocketry/airbrakeplugin/util/ComputedNavigableMap.java#L10)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

1. Add some comments to explain what ComputedSortedMap and ComputedMap are for
2. Maybe rename all of these to "lazy*"
3. See if anything exists in the stdlib
</blockquote></details>

Done. nothing in stdlib unfortunately

**Review by patrick-gu — COMMENTED** [review]
I think Christine and Kavin are happy here so I will merge now

> Dismissed @KavinSatheeskumar and @celery6 from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7#-:-NwXf_Rl6tUIsi5w_Qg6:b-mmzn26)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @celery6)

___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/simulated/SimulatedCdInterpolator.java` line 29 at r2](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/7#-NtseQ2S3JdiAA5ftw-p:-NwXfLzj6sofzV-92Ezf:b-juqpsl) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/0ed3549f8bc255f1fddb985ace77414b8a5fc707/src/main/java/com/waterloorocketry/airbrakeplugin/simulated/SimulatedCdInterpolator.java#L29)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

I think this is a consequence of the API design. We are essentially interpolating over new data each time, so we create a new interpolator. I agree that intuitively, it feels undesirable to instantiate a new linear interp calculator in each call. However, `ComputedNavigableMap` and `LinearInterpolator` are essentially designed to be free abstractions, in that they don't really do any unnecessary calculations in their constructors or methods. Especially with runtime optimization, this probably doesn't affect speed at all.
</blockquote></details>

Discussed with Kavin - added comment about the performance

**Review by celery6 — APPROVED** [review]

**Pull request merged**
