### PR TITLE
Trajectory prediction

### PR DESCRIPTION
**Pull request by ManavToor**
Implemented trajectory prediction.
Takes, vertical velocity, altitude, and coefficient of drag as inputs. Outputs max altitude.
Please check if I used the right index values from flightData.
I couldn't find where to pull coefficient of drag from so I just left it as 0.5 which I think is reasonable

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1)

### CODE REVIEW

**Review by celery6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ManavToor and @patrick-gu)

___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 3 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrR3kEbChIv_GxWZX_8:-NrR3kEbChIv_GxWZX_9:b-xiw85q) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L3)):*
> ```Java
> package com.waterloorocketry.airbrakeplugin.controller;
> 
> class TrajectoryPrediction {
> ```

Probably cleaner to put this class in a separate file.

Then, get_max_altitude() can be called [here](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/ddef96e0cbea59c0887e19ff7ed020fcffbf6fa7/src/main/java/com/waterloorocketry/airbrakeplugin/AirbrakePluginSimulationListener.java#L33C1-L33C51) and passed into the data array as altitude (assuming we always want to use predicted altitude instead of OR altitude?).

Also would reflect the actual board better since traj prediction is a separate thread
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 77 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrR8I2I89J_7ErQUu-r:-NrR8I2I89J_7ErQUu-s:b2s215o) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L77)):*
> ```Java
> 
>         // Fd = 0.5 * Cd * A * p * v^2
>         return -0.5 * drag_coef * ref_area * fluid_dens * velocity * velocity;
> ```

[code link](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/ddef96e0cbea59c0887e19ff7ed020fcffbf6fa7/src/main/java/com/waterloorocketry/airbrakeplugin/airbrake/Airbrakes.java#L15C1-L15C36)
is where CD is calculated given current conditions.

It's used in AirbrakePluginSimulationListener, so if traj prediction gets moved there then it should be able to access CD easier.
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 136 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrR9F6I7GjBlz9qO0-N:-NrR9F6I7GjBlz9qO0-O:biri45e) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L136)):*
> ```Java
>     @Override
>     public double calculateTargetExt(double[] flightData, double time) {
>         double altitude = new TrajectoryPrediction(flightData[4], flightData[1], 0.5).get_max_altitude();
> ```

Creating a new class every time the function is called is kind of not ideal. I think this would be avoided if traj prediction gets moved
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 136 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrRA4Gg-sCw-urt1U7s:-NrRA4Gg-sCw-urt1U7t:b6ydt8y) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L136)):*
> ```Java
>     @Override
>     public double calculateTargetExt(double[] flightData, double time) {
>         double altitude = new TrajectoryPrediction(flightData[4], flightData[1], 0.5).get_max_altitude();
> ```

Index values look right for vertical vel and pos!

**Review by patrick-gu — CHANGES_REQUESTED** [review]
Thanks for working on this! Let me know if you need anything

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-:-NrRp7x71UCFvNftKiTw:b-ivielc)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @celery6 and @ManavToor)

___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 6 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrRlnX_6lEcmo5P8aTh:-NrRlnXa-4H4PcvASOU3:b-lc9omx) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L6)):*
> ```Java
>     private static double velocity;
>     private static double altitude;
>     private static double drag_coef;
> ```

These variables probably should be instance variables instead of static
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 16 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrRmJLk7D3N-UBiANB0:-NrRmJLk7D3N-UBiANB1:b16uamd) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L16)):*
> ```Java
>     // Returns derivative of altitude (displacement): velocity
>     // This function is redundant, but it makes rk4 more intuitive
>     private static double altitude_derivative(double v) {
> ```

It would probably be cleaner to just change velocity -> altitude_derivative instead of having this function that does nothing
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 20 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrRmZBQ8r8zz39MtRqd:-NrRmZBQ8r8zz39MtRqe:b-ygqnqe) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L20)):*
> ```Java
>     }
> 
>     // Returns derivative of velocity: acceleration
> ```

These should be `/** */` Javadoc style comments so that you can write `@return`
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 77 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrR8I2I89J_7ErQUu-r:-NrRoYzWBKenpACUTm8H:bqrhbn) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L77)):*
<details><summary><i>Previously, celery6 (celery) wrote…</i></summary><blockquote>

[code link](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/ddef96e0cbea59c0887e19ff7ed020fcffbf6fa7/src/main/java/com/waterloorocketry/airbrakeplugin/airbrake/Airbrakes.java#L15C1-L15C36)
is where CD is calculated given current conditions.

It's used in AirbrakePluginSimulationListener, so if traj prediction gets moved there then it should be able to access CD easier.
</blockquote></details>

cd probably won't need to be a variable also then
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 85 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrRnGn1632Xe1KurAib:-NrRnGn1632Xe1KurAic:betgrmk) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L85)):*
> ```Java
>         double h = 0.01; // interval of change for rk4
> 
>         double mass = 39.564; // mass of rocket after burnout (kg)
> ```

For now this is fine but in the future we should probably get these values from OpenRocket, and then feed OpenRocket these values 
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 100 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrRolAI4EdYWcJzRQmH:-NrRolAI4EdYWcJzRQmI:bai3ib1) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L100)):*
> ```Java
> 
>             // update forces of drag and gravity from new altitude
>             Fd = drag_force();
> ```

In my opinion I think Fg and Fd could just be moved inside the loop, since I find it harder to read if we are using the Fg and Fd from the last iteration of the loop
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 136 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrR9F6I7GjBlz9qO0-N:-NrRn333DOC3oiwaEZoD:b-iooevc) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L136)):*
<details><summary><i>Previously, celery6 (celery) wrote…</i></summary><blockquote>

Creating a new class every time the function is called is kind of not ideal. I think this would be avoided if traj prediction gets moved
</blockquote></details>

I think it could be that get_max_altitude is a static method on TrajectoryPrediction (and all the other methods are private)

**Review by ManavToor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @celery6 and @patrick-gu)

___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 3 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrR3kEbChIv_GxWZX_8:-NrSEVxoBbgPMd906hk5:b-896fix) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L3)):*
<details><summary><i>Previously, celery6 (celery) wrote…</i></summary><blockquote>

Probably cleaner to put this class in a separate file.

Then, get_max_altitude() can be called [here](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/ddef96e0cbea59c0887e19ff7ed020fcffbf6fa7/src/main/java/com/waterloorocketry/airbrakeplugin/AirbrakePluginSimulationListener.java#L33C1-L33C51) and passed into the data array as altitude (assuming we always want to use predicted altitude instead of OR altitude?).

Also would reflect the actual board better since traj prediction is a separate thread
</blockquote></details>

Done.
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 6 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrRlnX_6lEcmo5P8aTh:-NrSEvBGA0QiApeJOJV4:b-896fix) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L6)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

These variables probably should be instance variables instead of static
</blockquote></details>

Done.
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 16 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrRmJLk7D3N-UBiANB0:-NrSEwJc6OxwLpST3zlk:b-2druri) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L16)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

It would probably be cleaner to just change velocity -> altitude_derivative instead of having this function that does nothing
</blockquote></details>

I removed the function altogether
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 20 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrRmZBQ8r8zz39MtRqd:-NrSF1zw7dDuXEc1-fCc:b-896fix) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L20)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

These should be `/** */` Javadoc style comments so that you can write `@return`
</blockquote></details>

Done.
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 77 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrR8I2I89J_7ErQUu-r:-NrSFHs_-_tWYL5ZUEcZ:b-th8db) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L77)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

cd probably won't need to be a variable also then
</blockquote></details>

I just left it the way it is now
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 85 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrRnGn1632Xe1KurAib:-NrSFLG34p1j2LqTufUb:b-3awi31) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L85)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

For now this is fine but in the future we should probably get these values from OpenRocket, and then feed OpenRocket these values
</blockquote></details>

h is a constant that just tunes the accuracy of the rk4 but I did turn mass into a parameter
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 100 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrRolAI4EdYWcJzRQmH:-NrSFfI_DcVplh1Dh3fU:b-896fix) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L100)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

In my opinion I think Fg and Fd could just be moved inside the loop, since I find it harder to read if we are using the Fg and Fd from the last iteration of the loop
</blockquote></details>

Done.
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 136 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrR9F6I7GjBlz9qO0-N:-NrSHLOM654YIALYFq75:baw7w3f) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L136)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

I think it could be that get_max_altitude is a static method on TrajectoryPrediction (and all the other methods are private)
</blockquote></details>

I added an updateInstance method. There is now a  TrajectoryPrediction object, expectedAltitude created at the begining of the code and every iteration, its values are just reset. Please veryify I defined in the proper location

**Review by patrick-gu — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1)* status: all files reviewed, 4 unresolved discussions (waiting on @celery6 and @ManavToor)

___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 20 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrRmZBQ8r8zz39MtRqd:-NrXChSkDtOTiqpFoRyz:b-ita104) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L20)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you also do it for the other ones too please? Mainly important for the public methods but private too would also be good

**Review by celery6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1)* status: all files reviewed, 4 unresolved discussions (waiting on @ManavToor and @patrick-gu)

___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 136 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrR9F6I7GjBlz9qO0-N:-NrXOEIx108Z13YSFb5g:b-kj8obn) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L136)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

I added an updateInstance method. There is now a  TrajectoryPrediction object, expectedAltitude created at the begining of the code and every iteration, its values are just reset. Please veryify I defined in the proper location
</blockquote></details>

I'm not sure this is the best place to define it. Calling getmaxalt() inside calculateTargetExt() makes it really awkward to unit test calculateTargetExt() since it's now dependant on another method (when we get around to writing more tests.. one day).

Would it work to define TrajectoryPred in SimulationListener and update it in PreStep? The data array is accessible there:
https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/ddef96e0cbea59c0887e19ff7ed020fcffbf6fa7/src/main/java/com/waterloorocketry/airbrakeplugin/AirbrakePluginSimulationListener.java#L38C1-L38C21

Everything else looks good!

**Review by ManavToor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @celery6 and @patrick-gu)

Just waiting for your aproval so I can merge
___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 136 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrR9F6I7GjBlz9qO0-N:-NrXdwxBCc0CqvKkaJNa:b-edvklc) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L136)):*
<details><summary><i>Previously, celery6 (celery) wrote…</i></summary><blockquote>

I'm not sure this is the best place to define it. Calling getmaxalt() inside calculateTargetExt() makes it really awkward to unit test calculateTargetExt() since it's now dependant on another method (when we get around to writing more tests.. one day).

Would it work to define TrajectoryPred in SimulationListener and update it in PreStep? The data array is accessible there:
https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/ddef96e0cbea59c0887e19ff7ed020fcffbf6fa7/src/main/java/com/waterloorocketry/airbrakeplugin/AirbrakePluginSimulationListener.java#L38C1-L38C21

Everything else looks good!
</blockquote></details>

That would require changing calculateTargetExt() in several places to add a predicted apogee parameter. I just went with @patrick-gu's original idea and made the method static

**Review by celery6 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @ManavToor and @patrick-gu)

___
*[`src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java` line 136 at r1](https://reviewable.io/reviews/waterloo-rocketry/or-airbrake-plugin/1#-NrR9F6I7GjBlz9qO0-N:-NrY3Wpp9r19txvl_dPP:b2uanjw) ([raw file](https://github.com/waterloo-rocketry/or-airbrake-plugin/blob/00f1111fc68d7ddad8c6b762f5adad01a9656336/src/main/java/com/waterloorocketry/airbrakeplugin/controller/PIDController.java#L136)):*
<details><summary><i>Previously, ManavToor (ManavToor) wrote…</i></summary><blockquote>

That would require changing calculateTargetExt() in several places to add a predicted apogee parameter. I just went with @patrick-gu's original idea and made the method static
</blockquote></details>

Oops wasn't clear - i was thinking to append it into the data array so it's passed in without modifying calculateTargetExt(). But that might make the data array more confusing which isn't great. Up to you.

Static works too though, so lgtm :thumbsup:

**Pull request merged**
